################################################################################################################################################# 
#                                                      
#                Project Euler problem 2
#    
#    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#
#
#
#################################################################################################################################################

def fibNumbers(numRange):
    listOfFibNumbers = []
    first = 0
    second = 1
    
    
    while second < numRange:
        newFib = first + second
        listOfFibNumbers.append(newFib)
        first = second
        second = newFib
        
    
    return listOfFibNumbers
    
def evenChecker(listOfFibNumbers):
    evenList = 0
    for item in listOfFibNumbers:
        if item < 4000000 and item % 2 == 0:
            evenList += item
    
    return evenList
    
#  answer = 4613732